#!/usr/bin/env node
// Build the self-bootstrapping single-file embed(s). Each widget compiles to one
// dist/*.js file: paste a <script> tag into a GHL Custom Code block and it
// injects styles + markup + logic into the page.
//
// Usage:
//   node scripts/build-embed.js          # build every widget
//   node scripts/build-embed.js assets   # build only one
//
// Mirrors the maxmethod/doc-rx-lookup build exactly so this repo is maintained
// the same way. dist/*.js are build artifacts — never hand-edit them.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CDN_REPO = 'maxmethod/ebotcpa-433a-widgets';

// One entry per widget. scope/containerId/guard/configGlobal must be unique so
// multiple embeds can coexist on the same GHL page without colliding.
const WIDGETS = {
  // Section 4 asset repeaters (config-driven engine) — each on its own page.
  investments: {
    input: 'investments.html',
    output: 'dist/embed-investments.js',
    containerId: 'investments-433a-widget',
    dataAttr: 'data-investments-433a-widget',
    styleAttr: 'data-investments-433a',
    guard: '__investments433aEmbedLoaded',
    label: 'investments'
  },
  digitalAssets: {
    input: 'digital-assets.html',
    output: 'dist/embed-digital-assets.js',
    containerId: 'digital-assets-433a-widget',
    dataAttr: 'data-digital-assets-433a-widget',
    styleAttr: 'data-digital-assets-433a',
    guard: '__digital433aEmbedLoaded',
    label: 'digital-assets'
  },
  availableCredit: {
    input: 'available-credit.html',
    output: 'dist/embed-available-credit.js',
    containerId: 'credit-433a-widget',
    dataAttr: 'data-credit-433a-widget',
    styleAttr: 'data-credit-433a',
    guard: '__credit433aEmbedLoaded',
    label: 'available-credit'
  },
  realProperty: {
    input: 'real-property.html',
    output: 'dist/embed-real-property.js',
    containerId: 'real-property-433a-widget',
    dataAttr: 'data-real-property-433a-widget',
    styleAttr: 'data-real-property-433a',
    guard: '__realprop433aEmbedLoaded',
    label: 'real-property'
  },
  personalAssets: {
    input: 'personal-assets.html',
    output: 'dist/embed-personal-assets.js',
    containerId: 'personal-assets-433a-widget',
    dataAttr: 'data-personal-assets-433a-widget',
    styleAttr: 'data-personal-assets-433a',
    guard: '__personal433aEmbedLoaded',
    label: 'personal-assets'
  },
  // Split widgets — each goes on its OWN page. These are the recommended embeds.
  bank: {
    input: 'bank-accounts.html',
    output: 'dist/embed-bank-accounts.js',
    containerId: 'bank-433a-widget',
    dataAttr: 'data-bank-433a-widget',
    styleAttr: 'data-bank-433a',
    guard: '__bank433aEmbedLoaded',
    label: 'bank-accounts'
  },
  vehicles: {
    input: 'vehicles.html',
    output: 'dist/embed-vehicles.js',
    containerId: 'vehicle-433a-widget',
    dataAttr: 'data-vehicle-433a-widget',
    styleAttr: 'data-vehicle-433a',
    guard: '__vehicle433aEmbedLoaded',
    label: 'vehicles'
  },
  // Legacy combined widget (bank + vehicles in one block). Kept for backward compat
  // with any v1.0.0 embed; new work should use the two split widgets above.
  assets: {
    input: 'assets-repeater.html',
    output: 'dist/embed-assets.js',
    containerId: 'assets-433a-widget',
    dataAttr: 'data-assets-widget',
    styleAttr: 'data-assets-repeater',
    guard: '__assets433aEmbedLoaded',
    label: 'assets-repeater'
  },
  // Module (style + script, NO container/markup): the slide-1 urgency-question card styler.
  // Finds the urgency radio group (data-q irs_intake_-_urgency_level) and restyles its three
  // options into selectable cards (badge/title/codes/SLA) + a "Why this matters" callout.
  // CSS is class-namespaced (.urg-*) so it doesn't need #id scoping. No mount div.
  urgencyCards: {
    input: 'urgency-cards.html',
    output: 'dist/embed-urgency-cards.js',
    styleAttr: 'data-433a-urgency',
    guard: '__urgencyCards433aLoaded',
    label: 'urgency-cards',
    module: true
  },
  // Module (style + script, NO container/markup): the income/expense live calculator.
  // It field-anchors itself (finds the total fields, injects its own card), so it needs
  // no mount div. Snapshot of the other session's tested calc — see income-expense-calc.html.
  incomeExpenseCalc: {
    input: 'income-expense-calc.html',
    output: 'dist/embed-income-expense-calc.js',
    styleAttr: 'data-433a-calc',
    guard: '__incomeExpense433aLoaded',
    label: 'income-expense-calc',
    module: true
  },

  // ── 433-B (Collection Information Statement for Businesses) — Company-object widgets ──
  // Same config-driven engine (generated by scripts/gen-433b-asset-widgets.js). One embed per
  // survey slide (no unified bundle for 433-B). containerId must match each file's CONFIG.containerId.
  b_bank:            { input: '433b-bank-accounts.html',        output: 'dist/embed-433b-bank-accounts.js',        containerId: 'bank-433b-widget',         dataAttr: 'data-bank-433b-widget',         styleAttr: 'data-bank-433b',         guard: '__bank433bEmbedLoaded',        label: '433b-bank-accounts' },
  b_ar:              { input: '433b-accounts-receivable.html',  output: 'dist/embed-433b-accounts-receivable.js',  containerId: 'ar-433b-widget',           dataAttr: 'data-ar-433b-widget',           styleAttr: 'data-ar-433b',           guard: '__ar433bEmbedLoaded',          label: '433b-accounts-receivable' },
  b_investments:     { input: '433b-investments.html',          output: 'dist/embed-433b-investments.js',          containerId: 'investments-433b-widget',  dataAttr: 'data-investments-433b-widget',  styleAttr: 'data-investments-433b',  guard: '__investments433bEmbedLoaded', label: '433b-investments' },
  b_digital:         { input: '433b-digital-assets.html',       output: 'dist/embed-433b-digital-assets.js',       containerId: 'digital-433b-widget',      dataAttr: 'data-digital-433b-widget',      styleAttr: 'data-digital-433b',      guard: '__digital433bEmbedLoaded',     label: '433b-digital-assets' },
  b_credit:          { input: '433b-available-credit.html',     output: 'dist/embed-433b-available-credit.js',     containerId: 'credit-433b-widget',       dataAttr: 'data-credit-433b-widget',       styleAttr: 'data-credit-433b',       guard: '__credit433bEmbedLoaded',      label: '433b-available-credit' },
  b_realprop:        { input: '433b-real-property.html',        output: 'dist/embed-433b-real-property.js',        containerId: 'realprop-433b-widget',     dataAttr: 'data-realprop-433b-widget',     styleAttr: 'data-realprop-433b',     guard: '__realprop433bEmbedLoaded',    label: '433b-real-property' },
  b_vehicles:        { input: '433b-vehicles.html',             output: 'dist/embed-433b-vehicles.js',             containerId: 'vehicle-433b-widget',      dataAttr: 'data-vehicle-433b-widget',      styleAttr: 'data-vehicle-433b',      guard: '__vehicle433bEmbedLoaded',     label: '433b-vehicles' },
  b_bizassets:       { input: '433b-business-assets.html',      output: 'dist/embed-433b-business-assets.js',      containerId: 'bizassets-433b-widget',    dataAttr: 'data-bizassets-433b-widget',    styleAttr: 'data-bizassets-433b',    guard: '__bizassets433bEmbedLoaded',   label: '433b-business-assets' },
  b_liabilities:     { input: '433b-business-liabilities.html', output: 'dist/embed-433b-business-liabilities.js', containerId: 'liabilities-433b-widget',  dataAttr: 'data-liabilities-433b-widget',  styleAttr: 'data-liabilities-433b',  guard: '__liab433bEmbedLoaded',        label: '433b-business-liabilities' },
  b_payment:         { input: '433b-payment-acceptance.html',   output: 'dist/embed-433b-payment-acceptance.js',   containerId: 'payment-433b-widget',      dataAttr: 'data-payment-433b-widget',      styleAttr: 'data-payment-433b',      guard: '__payment433bEmbedLoaded',     label: '433b-payment-acceptance' },
  b_personnel:       { input: '433b-personnel.html',            output: 'dist/embed-433b-personnel.js',            containerId: 'personnel-433b-widget',    dataAttr: 'data-personnel-433b-widget',    styleAttr: 'data-personnel-433b',    guard: '__personnel433bEmbedLoaded',   label: '433b-personnel' },
  b_loans:           { input: '433b-related-party-loans.html',  output: 'dist/embed-433b-related-party-loans.js',  containerId: 'loans-433b-widget',        dataAttr: 'data-loans-433b-widget',        styleAttr: 'data-loans-433b',        guard: '__loans433bEmbedLoaded',       label: '433b-related-party-loans' },
  b_transfers:       { input: '433b-asset-transfers.html',      output: 'dist/embed-433b-asset-transfers.js',      containerId: 'transfers-433b-widget',    dataAttr: 'data-transfers-433b-widget',    styleAttr: 'data-transfers-433b',    guard: '__transfers433bEmbedLoaded',   label: '433b-asset-transfers' },
  b_affiliations:    { input: '433b-affiliations.html',         output: 'dist/embed-433b-affiliations.js',         containerId: 'affiliations-433b-widget', dataAttr: 'data-affiliations-433b-widget', styleAttr: 'data-affiliations-433b', guard: '__affil433bEmbedLoaded',       label: '433b-affiliations' },
  b_lawsuit:         { input: '433b-lawsuit.html',              output: 'dist/embed-433b-lawsuit.js',              containerId: 'lawsuit-433b-widget',      dataAttr: 'data-lawsuit-433b-widget',      styleAttr: 'data-lawsuit-433b',      guard: '__lawsuit433bEmbedLoaded',     label: '433b-lawsuit' },
  b_bankruptcy:      { input: '433b-bankruptcy.html',           output: 'dist/embed-433b-bankruptcy.js',           containerId: 'bankruptcy-433b-widget',   dataAttr: 'data-bankruptcy-433b-widget',   styleAttr: 'data-bankruptcy-433b',   guard: '__bankruptcy433bEmbedLoaded',  label: '433b-bankruptcy' },
  // 433-B Section 5 income/expense/net calc (field-anchored module, no mount div).
  b_incomeExpenseCalc: {
    input: '433b-income-expense-calc.html',
    output: 'dist/embed-433b-income-expense-calc.js',
    styleAttr: 'data-433b-calc',
    guard: '__incomeExpense433bLoaded',
    label: '433b-income-expense-calc',
    module: true
  }
};

// Scope every selector to #<containerId> so the widget's CSS cannot leak out and
// affect the host page. We DOUBLE the scope id (#x#x) to bump specificity above
// typical host-page form-framework rules — the cheapest way to win the cascade
// against e.g. GHL's form styles without resorting to !important. Two ID
// selectors on the same element is valid CSS and doubles the specificity weight.
// Keeps :root custom-property declarations global; drops body/html rules.
function scopeCss(css, scope) {
  css = css.replace(/\/\*[\s\S]*?\*\//g, '');  // strip CSS comments
  const compound = `${scope}${scope}`;
  return css.replace(/([^{}]+)\{([^{}]*)\}/g, (match, selector, body) => {
    const sel = selector.trim();
    if (sel === ':root') return `${sel} {${body}}`;
    if (sel === 'body' || sel === 'html' || sel === 'html, body') return '';
    const scoped = sel.split(',').map(part => {
      const trimmed = part.trim();
      if (!trimmed) return trimmed;
      if (trimmed.startsWith(scope)) return trimmed;
      return `${compound} ${trimmed}`;
    }).join(', ');
    return `${scoped} {${body}}`;
  });
}

const escapeForTemplate = s =>
  s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

function build(widget) {
  const input = path.resolve(ROOT, widget.input);
  const output = path.resolve(ROOT, widget.output);
  const html = fs.readFileSync(input, 'utf8');
  const scope = `#${widget.containerId}`;

  const styleMatch = html.match(/<style>([\s\S]*?)<\/style>/);
  if (!styleMatch) throw new Error(`[${widget.label}] Could not find <style> block`);
  const css = scopeCss(styleMatch[1].trim(), scope);

  const bodyMatch = html.match(/<body>([\s\S]*?)<\/body>/);
  if (!bodyMatch) throw new Error(`[${widget.label}] Could not find <body> block`);
  let body = bodyMatch[1].trim();

  const scriptMatch = body.match(/<script>([\s\S]*?)<\/script>/);
  if (!scriptMatch) throw new Error(`[${widget.label}] Could not find <script> block in body`);
  const js = scriptMatch[1].trim();
  body = body.replace(scriptMatch[0], '').trim();

  const embed = `/**
 * ${widget.label} embed bootstrap
 * Generated from ${widget.input} by scripts/build-embed.js — do not hand-edit.
 *
 * Drop into a GHL form step (Custom Code element) with:
 *   <div id="${widget.containerId}" data-primary-color="{{custom_values.brand_primary_color}}"></div>
 *   <script src="https://cdn.jsdelivr.net/gh/${CDN_REPO}@vX.Y.Z/${widget.output}"></script>
 *
 * Or omit the <div> and the script appends the widget to <body>.
 */
(function () {
  if (window.${widget.guard}) return;
  window.${widget.guard} = true;

  // ---- styles ----
  const style = document.createElement('style');
  style.setAttribute('${widget.styleAttr}', 'styles');
  style.textContent = \`${escapeForTemplate(css)}\`;
  document.head.appendChild(style);

  // ---- markup ----
  let container = document.getElementById('${widget.containerId}') ||
                  document.querySelector('[${widget.dataAttr}]');
  if (!container) {
    container = document.createElement('div');
    container.id = '${widget.containerId}';
    container.setAttribute('data-ar-autoplaced', '1'); // engine may relocate next to its host field (true paste-once)
    document.body.appendChild(container);
  }
  container.innerHTML = \`${escapeForTemplate(body)}\`;

  // ---- widget logic ----
  (function widgetMain() {
${js}
  })();
})();
`;

  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, embed);
  const kb = (fs.statSync(output).size / 1024).toFixed(1);
  console.log(`[${widget.label}] wrote ${widget.output} (${kb} KB)`);
}

// Build a module that has styles + a script but NO container/markup (e.g. the
// income/expense calc, which field-anchors itself and injects its own card). Produces a
// guarded IIFE that injects the <style> and runs the <script>. CSS is left global on
// purpose (the calc's .mm-calc-card is its own namespace and is owned by another session).
function buildModule(widget) {
  const input = path.resolve(ROOT, widget.input);
  const output = path.resolve(ROOT, widget.output);
  const html = fs.readFileSync(input, 'utf8');

  const styleMatch = html.match(/<style>([\s\S]*?)<\/style>/);
  const css = styleMatch ? styleMatch[1].trim() : '';
  const scriptMatch = html.match(/<script>([\s\S]*?)<\/script>/);
  if (!scriptMatch) throw new Error(`[${widget.label}] Could not find <script> block`);
  const js = scriptMatch[1].trim();

  const styleInject = css ? `  const style = document.createElement('style');
  style.setAttribute('${widget.styleAttr}', 'styles');
  style.textContent = \`${escapeForTemplate(css)}\`;
  document.head.appendChild(style);

` : '';

  const embed = `/**
 * ${widget.label} module
 * Generated from ${widget.input} by scripts/build-embed.js — do not hand-edit.
 * Styles + behavior, no mount <div> (it field-anchors itself). Paste once, anywhere.
 *   <script src="https://cdn.jsdelivr.net/gh/${CDN_REPO}@vX.Y.Z/${widget.output}"></script>
 */
(function () {
  if (window.${widget.guard}) return;
  window.${widget.guard} = true;

${styleInject}${js}
})();
`;
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, embed);
  const kb = (fs.statSync(output).size / 1024).toFixed(1);
  console.log(`[${widget.label}] wrote ${widget.output} (${kb} KB) [module]`);
}

// ---- Unified bundle: all asset repeaters + the income/expense calc in ONE paste-in script ----
// Each part is a self-contained, guarded IIFE (repeaters scoped to their own #container;
// the calc field-anchors + namespaces its own card), so concatenating them is safe — pasting
// this one <script> once drives everything. Survey-step order (13→20, then the calc). The
// legacy combined 'assets' embed is excluded (it would double up bank + vehicles).
const BUNDLE = {
  output: 'dist/embed-433a.js',
  parts: ['bank', 'investments', 'digitalAssets', 'availableCredit', 'realProperty', 'vehicles', 'personalAssets', 'incomeExpenseCalc'],
  label: '433a-bundle'
};
function buildBundle() {
  const header = `/**
 * 433-A UNIFIED BUNDLE — every asset repeater + the income/expense calc in ONE paste-in script.
 * Generated by scripts/build-embed.js — do not hand-edit. Concatenation of the individual
 * dist/embed-*.js modules; each is a self-contained, guarded IIFE (repeaters scoped to their
 * own #container, calc namespaced to .mm-calc-card), so they coexist with no collisions.
 *
 * TRUE PASTE-ONCE: paste this ONE <script> once (anywhere — every survey step shares one DOM).
 * No mount <div>s required: each repeater finds its native LARGE_TEXT host field (matched by
 * clean key) and renders itself right there; the calc finds its total fields and injects its card.
 * Just have the native fields on their steps.
 *   <script src="https://cdn.jsdelivr.net/gh/${CDN_REPO}@vX.Y.Z/${BUNDLE.output}"></script>
 * Modules: ${BUNDLE.parts.join(', ')}.
 */
`;
  const chunks = BUNDLE.parts.map(name => {
    const w = WIDGETS[name];
    if (!w) throw new Error(`[bundle] unknown part "${name}"`);
    const p = path.resolve(ROOT, w.output);
    if (!fs.existsSync(p)) throw new Error(`[bundle] missing ${w.output} — run a full build first`);
    const tag = w.containerId ? '#' + w.containerId : 'module';
    return `\n/* ===================== ${w.label} (${tag}) ===================== */\n` + fs.readFileSync(p, 'utf8').trim() + '\n';
  });
  const outPath = path.resolve(ROOT, BUNDLE.output);
  const out = header + chunks.join('\n');
  fs.writeFileSync(outPath, out);
  console.log(`[${BUNDLE.label}] wrote ${BUNDLE.output} (${(out.length / 1024).toFixed(1)} KB) — ${BUNDLE.parts.length} modules`);
}

const only = process.argv[2];
if (only === 'bundle') {
  // Rebuild every part FIRST so `build-embed.js bundle` can't ship stale modules from dist/,
  // then concatenate. (A full `build-embed.js` already builds all parts before bundling.)
  for (const name of BUNDLE.parts) { const w = WIDGETS[name]; (w.module ? buildModule : build)(w); }
  buildBundle();
  process.exit(0);
}
const names = only ? [only] : Object.keys(WIDGETS);
for (const name of names) {
  const w = WIDGETS[name];
  if (!w) { console.error(`Unknown widget "${name}". Known: ${Object.keys(WIDGETS).join(', ')}, bundle`); process.exit(1); }
  (w.module ? buildModule : build)(w);
}
if (!only) buildBundle();
